export interface AdminUser {
  id: string;
  name: string;
  phone: string;
  email: string;
  joinedDate: string;
  lastRenewalDate: string;
  nextRenewalDate: string;
  subDomain: string;
  renewalAmount: number;
  city: string;
  rolesAccess: string[];
  status: "Active" | "Inactive" | "Expired";
}

export interface PendingRequest {
  id: string;
  name: string;
  phone: string;
  email: string;
  desc: string;
  notes: string;
  status: "Accepted" | "In-progress" | "Pending" | "Canceled";
  createdDate: string;
  city: string;
}

export interface RenewalItem {
  id: string;
  adminId: string;
  adminName: string;
  businessName: string;
  renewalDate: string;
  amount: number;
  lastNotificationSent?: string;
  city: string;
  status: "Due Soon" | "Overdue" | "Upcoming" | "Completed";
}

export interface DashboardFilterState {
  dateRange: "all" | "today" | "week" | "month" | "year";
  city: string;
  searchQuery: string;
}

// ── Initial Mock Data ────────────────────────────────────────────────────────
export const INITIAL_ADMINS: AdminUser[] = [
  {
    id: "ADM-001",
    name: "Rajesh Sharma",
    phone: "+91 98765 43210",
    email: "rajesh.sharma@nahargarh.com",
    joinedDate: "2021-01-15",
    lastRenewalDate: "2026-01-15",
    nextRenewalDate: "2027-01-15",
    subDomain: "nahargarh.ticketing.com",
    renewalAmount: 45000,
    city: "Jaipur",
    rolesAccess: ["Ticket Booking", "Bookings", "Transactions", "Invoices", "Reports"],
    status: "Active",
  },
  {
    id: "ADM-002",
    name: "Priya Verma",
    phone: "+91 98123 45678",
    email: "priya.verma@citypalace.com",
    joinedDate: "2016-03-20",
    lastRenewalDate: "2026-03-20",
    nextRenewalDate: "2027-03-20",
    subDomain: "citypalace.ticketing.com",
    renewalAmount: 60000,
    city: "Udaipur",
    rolesAccess: ["Bookings", "Inventory / Capacity", "Customer Management", "Reports"],
    status: "Active",
  },
  {
    id: "ADM-003",
    name: "Amitabh Mehta",
    phone: "+91 97654 32109",
    email: "amitabh@fortview.org",
    joinedDate: "2021-06-10",
    lastRenewalDate: "2026-06-10",
    nextRenewalDate: "2027-06-10",
    subDomain: "fortview.ticketing.com",
    renewalAmount: 38000,
    city: "Jodhpur",
    rolesAccess: ["Ticket Booking", "Bookings", "CCTV Monitoring"],
    status: "Active",
  },
  {
    id: "ADM-004",
    name: "Sunita Roy",
    phone: "+91 99887 76655",
    email: "sunita.r@delhiattractions.in",
    joinedDate: "2020-09-01",
    lastRenewalDate: "2025-09-01",
    nextRenewalDate: "2026-09-01",
    subDomain: "delhimuseum.ticketing.com",
    renewalAmount: 52000,
    city: "Delhi",
    rolesAccess: ["Ticket Booking", "Invoices", "Complimentary Passes", "Reports"],
    status: "Active",
  },
  {
    id: "ADM-005",
    name: "Vikramaditya Singh",
    phone: "+91 91234 56789",
    email: "vikram@mumbaifunpark.com",
    joinedDate: "2019-11-12",
    lastRenewalDate: "2025-11-12",
    nextRenewalDate: "2026-11-12",
    subDomain: "mumbaifunpark.ticketing.com",
    renewalAmount: 75000,
    city: "Mumbai",
    rolesAccess: ["Ticket Booking", "Attraction Management", "User Management", "Settings", "Backup"],
    status: "Active",
  },
  {
    id: "ADM-006",
    name: "Suresh Raina",
    phone: "+91 98221 10099",
    email: "suresh@hawamahal.org",
    joinedDate: "2022-04-18",
    lastRenewalDate: "2025-04-18",
    nextRenewalDate: "2026-08-30",
    subDomain: "hawamahal.ticketing.com",
    renewalAmount: 42000,
    city: "Jaipur",
    rolesAccess: ["Ticket Booking", "Bookings", "Reports"],
    status: "Active",
  },
  {
    id: "ADM-007",
    name: "Neha Kapoor",
    phone: "+91 97112 23344",
    email: "neha.k@redforttours.com",
    joinedDate: "2018-07-05",
    lastRenewalDate: "2024-07-05",
    nextRenewalDate: "2025-07-05",
    subDomain: "redfort.ticketing.com",
    renewalAmount: 58000,
    city: "Delhi",
    rolesAccess: ["Ticket Booking", "Invoices", "Complimentary Passes"],
    status: "Expired",
  },
  {
    id: "ADM-008",
    name: "Alok Trivedi",
    phone: "+91 96543 88776",
    email: "alok@gatewaycruises.com",
    joinedDate: "2023-02-14",
    lastRenewalDate: "2026-02-14",
    nextRenewalDate: "2027-02-14",
    subDomain: "gatewaycruises.ticketing.com",
    renewalAmount: 82000,
    city: "Mumbai",
    rolesAccess: ["Ticket Booking", "Bookings", "Customer Management"],
    status: "Active",
  },
  {
    id: "ADM-009",
    name: "Kavita Joshi",
    phone: "+91 95432 11009",
    email: "kavita@lakepichola.in",
    joinedDate: "2021-08-22",
    lastRenewalDate: "2025-08-22",
    nextRenewalDate: "2026-08-28",
    subDomain: "lakepichola.ticketing.com",
    renewalAmount: 49000,
    city: "Udaipur",
    rolesAccess: ["Ticket Booking", "Inventory / Capacity", "Reports"],
    status: "Active",
  },
  {
    id: "ADM-010",
    name: "Manish Malhotra",
    phone: "+91 94321 66554",
    email: "manish@mehrangarh.org",
    joinedDate: "2020-05-30",
    lastRenewalDate: "2026-05-30",
    nextRenewalDate: "2027-05-30",
    subDomain: "mehrangarh.ticketing.com",
    renewalAmount: 51000,
    city: "Jodhpur",
    rolesAccess: ["Ticket Booking", "Bookings", "CCTV Monitoring"],
    status: "Active",
  },
  {
    id: "ADM-011",
    name: "Pooja Hegde",
    phone: "+91 93210 99887",
    email: "pooja@amerfortnight.com",
    joinedDate: "2022-10-10",
    lastRenewalDate: "2025-10-10",
    nextRenewalDate: "2026-10-10",
    subDomain: "amerfort.ticketing.com",
    renewalAmount: 46000,
    city: "Jaipur",
    rolesAccess: ["Ticket Booking", "Complimentary Passes"],
    status: "Active",
  },
  {
    id: "ADM-012",
    name: "Rohan Shrestha",
    phone: "+91 92109 44332",
    email: "rohan@esselworld.com",
    joinedDate: "2017-12-01",
    lastRenewalDate: "2024-12-01",
    nextRenewalDate: "2025-12-01",
    subDomain: "esselworld.ticketing.com",
    renewalAmount: 89000,
    city: "Mumbai",
    rolesAccess: ["Ticket Booking", "Attraction Management", "Backup"],
    status: "Inactive",
  },
];

export const INITIAL_PENDING_REQUESTS: PendingRequest[] = [
  {
    id: "REQ-101",
    name: "Karan Johar",
    phone: "+91 98450 11223",
    email: "karan@royalheritagetours.com",
    desc: "Requesting super admin authorization for new theme park domain setup.",
    notes: "Followed up via call. Requires approval by Friday.",
    status: "Pending",
    createdDate: "2026-08-01",
    city: "Jaipur",
  },
  {
    id: "REQ-102",
    name: "Meenakshi Sundaram",
    phone: "+91 97311 88990",
    email: "meenakshi@palacevents.in",
    desc: "Upgrading server tier for monsoon festival traffic increase.",
    notes: "Payment gateway verified. In review by devops team.",
    status: "In-progress",
    createdDate: "2026-08-03",
    city: "Udaipur",
  },
  {
    id: "REQ-103",
    name: "Devendra Rathore",
    phone: "+91 99001 22334",
    email: "devendra@desertsafari.com",
    desc: "Addition of 5 new counter staff roles and complimentary pass quota.",
    notes: "Approved after compliance check.",
    status: "Accepted",
    createdDate: "2026-07-28",
    city: "Jodhpur",
  },
  {
    id: "REQ-104",
    name: "Ananya Gupta",
    phone: "+91 96112 33445",
    email: "ananya@delhiwaterpark.com",
    desc: "Domain alias update to waterpark-delhi.com.",
    notes: "Canceled due to incorrect documentation submitted.",
    status: "Canceled",
    createdDate: "2026-07-25",
    city: "Delhi",
  },
  {
    id: "REQ-105",
    name: "Hardik Patel",
    phone: "+91 95223 44556",
    email: "hardik@mumbaipark.com",
    desc: "New POS terminal integration request for counter 3 and 4.",
    notes: "Pending security check.",
    status: "Pending",
    createdDate: "2026-08-04",
    city: "Mumbai",
  },
  {
    id: "REQ-106",
    name: "Sneha Agarwal",
    phone: "+91 94334 55667",
    email: "sneha@jaipurexhibits.org",
    desc: "Requesting increase in daily booking quota for heritage week.",
    notes: "Under review by capacity team.",
    status: "In-progress",
    createdDate: "2026-08-02",
    city: "Jaipur",
  },
  {
    id: "REQ-107",
    name: "Rahul Dravid",
    phone: "+91 93445 66778",
    email: "rahul@delhisportscomplex.com",
    desc: "Super Admin authorization for multi-gate QR Scanner API.",
    notes: "Awaiting domain verification.",
    status: "Pending",
    createdDate: "2026-08-05",
    city: "Delhi",
  },
  {
    id: "REQ-108",
    name: "Divya Khosla",
    phone: "+91 92556 77889",
    email: "divya@udaipurboating.in",
    desc: "Enabling UPI payment gateway extension.",
    notes: "Completed testing successfully.",
    status: "Accepted",
    createdDate: "2026-07-30",
    city: "Udaipur",
  },
  {
    id: "REQ-109",
    name: "Tarun Mansukhani",
    phone: "+91 91667 88990",
    email: "tarun@jodhpurfolk.org",
    desc: "Addition of VIP fast-track booking module.",
    notes: "Requires senior review.",
    status: "Pending",
    createdDate: "2026-08-05",
    city: "Jodhpur",
  },
  {
    id: "REQ-110",
    name: "Ritu Kumar",
    phone: "+91 90778 99001",
    email: "ritu@mumbaimuseums.com",
    desc: "Sub-domain migration request to museum-mumbai.com.",
    notes: "DNS propagation in progress.",
    status: "In-progress",
    createdDate: "2026-08-04",
    city: "Mumbai",
  },
];

export const INITIAL_RENEWALS: RenewalItem[] = [
  {
    id: "REN-201",
    adminId: "ADM-003",
    adminName: "Amitabh Mehta",
    businessName: "Fort View Jodhpur",
    renewalDate: "2026-08-25",
    amount: 38000,
    city: "Jodhpur",
    status: "Due Soon",
  },
  {
    id: "REN-202",
    adminId: "ADM-004",
    adminName: "Sunita Roy",
    businessName: "Delhi Heritage Museum",
    renewalDate: "2025-09-01",
    amount: 52000,
    city: "Delhi",
    status: "Upcoming",
  },
  {
    id: "REN-203",
    adminId: "ADM-005",
    adminName: "Vikramaditya Singh",
    businessName: "Mumbai Fun Park",
    renewalDate: "2025-11-12",
    amount: 75000,
    city: "Mumbai",
    status: "Upcoming",
  },
  {
    id: "REN-204",
    adminId: "ADM-001",
    adminName: "Rajesh Sharma",
    businessName: "Nahargarh Fort Palace",
    renewalDate: "2026-01-15",
    amount: 45000,
    city: "Jaipur",
    status: "Upcoming",
  },
  {
    id: "REN-205",
    adminId: "ADM-002",
    adminName: "Priya Verma",
    businessName: "City Palace Ticket Hub",
    renewalDate: "2026-03-20",
    amount: 60000,
    city: "Udaipur",
    status: "Upcoming",
  },
  {
    id: "REN-206",
    adminId: "ADM-006",
    adminName: "Suresh Raina",
    businessName: "Jaipur Hawa Mahal Tour",
    renewalDate: "2026-08-30",
    amount: 42000,
    city: "Jaipur",
    status: "Due Soon",
  },
  {
    id: "REN-207",
    adminId: "ADM-007",
    adminName: "Neha Kapoor",
    businessName: "Red Fort Lights & Sound",
    renewalDate: "2025-07-05",
    amount: 58000,
    city: "Delhi",
    status: "Overdue",
  },
  {
    id: "REN-208",
    adminId: "ADM-008",
    adminName: "Alok Trivedi",
    businessName: "Gateway of India Cruises",
    renewalDate: "2027-02-14",
    amount: 82000,
    city: "Mumbai",
    status: "Upcoming",
  },
  {
    id: "REN-209",
    adminId: "ADM-009",
    adminName: "Kavita Joshi",
    businessName: "Lake Pichola Water Rides",
    renewalDate: "2026-08-28",
    amount: 49000,
    city: "Udaipur",
    status: "Due Soon",
  },
  {
    id: "REN-210",
    adminId: "ADM-010",
    adminName: "Manish Malhotra",
    businessName: "Mehrangarh Museum Pass",
    renewalDate: "2027-05-30",
    amount: 51000,
    city: "Jodhpur",
    status: "Upcoming",
  },
  {
    id: "REN-211",
    adminId: "ADM-011",
    adminName: "Pooja Hegde",
    businessName: "Amer Fort Night Safari",
    renewalDate: "2026-10-10",
    amount: 46000,
    city: "Jaipur",
    status: "Upcoming",
  },
  {
    id: "REN-212",
    adminId: "ADM-012",
    adminName: "Rohan Shrestha",
    businessName: "Essel World Express Line",
    renewalDate: "2025-12-01",
    amount: 89000,
    city: "Mumbai",
    status: "Overdue",
  },
];
